spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  jpa:
    # Provide database platform that is being used
    # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # New database is created when app starts and destroyed when app stops
      ddl-auto: create-drop
    # Show sql when spring data jpa performs query
    show-sql: false
    properties:
      hibernate:
        # Format queries
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: ${API_ENDPOINT:http://localhost:8080}
    title: API Service Documents
    version: '1.0.0'