server:
  port: 8080
spring:
  application:
    name: api-service
  profiles:
    active: @spring.profiles.active@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

logging:
  level:
    root: INFO
    web: OFF
    org.springframework: OFF